name: Backend build&test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Artefact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file pom.xml -DskipTests
        working-directory: inventory-management
      - run: mkdir staging && cp target/*.jar staging/backend.jar
        working-directory: inventory-management
      - uses: actions/upload-artifact@v1
        with:
          name: backend_jar
          path: backend/staging

  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run tests
        working-directory: ./inventory-management
        run: mvn -B test
