name: Backend build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Artefact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -B package --file pom.xml -DskipTests
        working-directory: inventory-management
      - run: mkdir staging && cp target/*.jar staging/backend.jar
        working-directory: inventory-management
      - uses: actions/upload-artifact@v1
        with:
          name: backend_jar
          path: inventory-management/staging
      - name: sonarQA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -DskipTests -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=winter-school -Dsonar.qualitygate.wait=true
        working-directory: inventory-management




